services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    App\Modules\Agency\:
        resource: '../'
        exclude:
            - '../Action/'
            - '../Entity/'
            - '../QueryScope'
    
    
    App\Modules\Agency\Action\:
        resource: '../Action/'
        tags: [ 'controller.service_arguments' ]
